### ISSUE TITLE
SCA - Software Composition Analysis

### ISSUE THREAD

**Issue by raphaelhagi** [OWASP/DevSecOpsGuideline#11]
Hello there,

I would like to propose to add a SCA scanning close do SAST. Many security problems in software are related with libs with opened CVE issues.

**Comment by myugan** [comment]
Its already here https://github.com/OWASP/DevSecOpsGuideline/blob/master/document/02a-Static%20scanning.md but only mentioned the tools. We can separate those things as another part as "Software Component Analysis".

**Comment by Ali-Yazdani** [comment]
Hi, 
@raphaelhagi I think the "Tools (Dependency scanning)" in https://github.com/OWASP/DevSecOpsGuideline/blob/master/document/02a-Static%20scanning.md has covered this already. Definitely, it needs improvement but if you think it should be separated or rename required let me know. 

@myugan  yeah, we can discuss the document structure.

**Comment by Ali-Yazdani** [comment]
It covers in https://github.com/OWASP/DevSecOpsGuideline/blob/master/document/02d-Software-Composition-Analysis.md
