### ISSUE TITLE
Add privacy to the security guideline

### ISSUE THREAD

**Issue by SudE29537** [OWASP/DevSecOpsGuideline#16]
Since we are dealing with several privacy laws and regulations, I believe it makes sense to add a privacy component to the DevSecOps security guideline.

**Comment by Ali-Yazdani** [comment]
Sounds good,
Could you please share some example

**Comment by SudE29537** [comment]
Something like this:

" Privacy has become a major topic for companies of all sizes, since GDPR (Europe’s General Data Protection Regulations), CCPA (California Consumer Privacy Act), LGPD – Brazil’s Lei Geral de Proteção de Dados, and other laws and regulations are being enforced around the world.

Applications that will process a large volume of PII (personally identifiable information) should adapt the DevSecOps to follow the Privacy by Design approach, where the development process addresses privacy concerns thru the whole cycle.

To start, it is important to have a good understanding of what is considered PII:

- First and last name;
- Identifiable email (name.lastname@domain.com);
- Identity card numbers;
- Location data (mobile);
- IP Address.

This is not a complete list.

You have to create a PII data flow to make sure you apply the required protection to the data thru its lifecicle. You also have to follow all the requirements related to the quality and volume of processed data. "

If you believe it makes sense I can add more details and submit them.

**Comment by Ali-Yazdani** [comment]
Sounds good. please add this part

**Comment by SudE29537** [comment]
Are we creating another document specifically to this subject, or we'll add it to an existing one? If the latter, to which? Overview?
