### ISSUE TITLE
Discord channel 

### ISSUE THREAD

**Issue by Ali-Yazdani** [OWASP/DevSecOpsGuideline#17]
I wanna create a Discord channel as a place for communication and planning for this project.
What's your comment? 
@CirKu17 @ioggstream  @SudE29537 @vanderaj @raphaelhagi

**Comment by SudE29537** [comment]
I'm not very active on Discord, but it works for me.

**Comment by coadaflorin** [comment]
@Ali-Yazdani is there a channel up and running on discord, slack or anything?

**Comment by Ali-Yazdani** [comment]
@coadaflorin @SudE29537  sorry for the late reply. happy new year. 

https://discord.gg/CwAsRSfJ

**Comment by mhmatthewhugley** [comment]
> @coadaflorin @SudE29537 sorry for the late reply. happy new year.
> 
> https://discord.gg/CwAsRSfJ

It is expired.
