### ISSUE TITLE
Reuse the OWASP tool lists 

### ISSUE THREAD

**Issue by coadaflorin** [OWASP/DevSecOpsGuideline#19]
I noticed that the SAST & DAST document lists a few tools. 
Would it not be better to reuse the existing OWASP lists for this? Keeps just one source to maintain all of this data. 
SAST list: https://owasp.org/www-community/Source_Code_Analysis_Tools
DAST list: https://owasp.org/www-community/Vulnerability_Scanning_Tools.

**Comment by Ali-Yazdani** [comment]
@coadaflorin Thanks for sharing the lists but our final goal is preparing a corporation table of tools that shows which one able to integrate with which automation tools. For Ex, which one able to work with Azure DevOps pipeline, Jenkins, Github, and  ...

**Comment by coadaflorin** [comment]
Ok, that makes sense. Is the plan to manually go through different tools and link what integrates with what or ask vendors to contribute where possible to fill in the info for their own tools?

**Comment by Ali-Yazdani** [comment]
We can ask them to add their tool capability but also this part can be drive by us.
