### ISSUE TITLE
Adding IAST - Interactive Analysis 

### ISSUE THREAD

**Issue by coadaflorin** [OWASP/DevSecOpsGuideline#20]
I see no mention of IAST on the tools lists. 
It's a very powerful technique that people could benefit from, especially if they already have some automated functional testing. Technically it's much faster than DAST and the sync between HTTP requests and stack is very useful in debugging. 

Location:
As soon as you have something running you can do IAST on it. So I'd say potentially right next to or before the DAST component. Also, if you do DAST and perform some automatic crawl of the application a lot of times that will help the IAST tool. IAST is dependent on external traffic to have something to monitor.

**Comment by coadaflorin** [comment]
Happy to join. What's the process?

**Comment by Ali-Yazdani** [comment]
Good to hearing this. just make your PR.
