### ISSUE TITLE
How to access the document

### ISSUE THREAD

**Issue by isouza-daitan** [OWASP/DevSecOpsGuideline#43]
Hi, is there a place where the full documentation is available for easy consumption as a web page or PDF?

I can go through the markdown files on the `document` folder but I feel like there should be a consolidated document published somewhere (maybe the [OWASP project page](https://owasp.org/www-project-devsecops-guideline/)?) to make it easier to read and reference.

**Comment by Ali-Yazdani** [comment]
Hi, 
Sounds good. 
My assumption was to publish it as a PDF but the webpage under the project page also is good. let's make the documents ready for publication and then publish them. this is part of this year's plan.

**Comment by Ali-Yazdani** [comment]
Hi @isouza-daitan, 
Right now, we want to have a web version of the documents. 
@CirKu17 What's your opinion?

**Comment by Ali-Yazdani** [comment]
Hi, A version is available now. 
https://owasp.org/www-project-devsecops-guideline/latest/
