### ISSUE TITLE
Adding Application Vulnerability Management

### ISSUE THREAD

**Issue by dnavarrom** [OWASP/DevSecOpsGuideline#45]
Hi, 

I think we could add something related to the DevSecOps program management and metrics. Since the success of DevSecOps efforts on teams or enterprises relies on things like adoption, number of vulnerabilities, the time it takes to remediate the issues, etc. Application Vulnerability Management could be a good touchpoint to add to this guide.

We can look at:
* https://www.defectdojo.org/
* https://defectdojo.github.io/django-DefectDojo/usage/models/

**Comment by Ali-Yazdani** [comment]
Hi,
Make sense.  Please add a file for VM under section 2. if you can't let me do it. 

Thanks

**Comment by Ali-Yazdani** [comment]
Addressed by https://github.com/OWASP/DevSecOpsGuideline/pull/53
Done.
