### ISSUE TITLE
Add CI/CD to deploy https://owasp.org/www-project-devsecops-guideline

### ISSUE THREAD

**Issue by sergiomarotco** [OWASP/DevSecOpsGuideline#66]
The current version of the site differs from the source code here on github

**Comment by Ali-Yazdani** [comment]
Yeah, after updating documents in this repo, I'll prepare a new release for the website version as well. 
So we always have some different things here and web version.

**Comment by sergiomarotco** [comment]
I propose to implement a CI/CD pipeline for automatic site deployment

**Comment by Ali-Yazdani** [comment]
Good idea, but we don't want to publish everything there, sometimes we need to trim the document before posting it so a publish branch or tag can help.

**Comment by sergiomarotco** [comment]
As you wish, I just suggested

**Comment by Ali-Yazdani** [comment]
Hi @sergiomarotco ,
I just share my comment about it. if you want to work on that, the door is still open. (we need to use a separate branch for publishing doc)
